# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'RNFS', :path => '../node_modules/react-native-fs'

    #pod 'RNI18n', :path => '../node_modules/react-native-i18n'

    #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    #pod 'RNSound', :path => '../node_modules/react-native-sound'

    #pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  end

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


